# Generated by Django 2.2.1 on 2019-05-16 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 5, 16, 11, 57, 7, 145731))),
                ('content', models.CharField(max_length=3000)),
                ('toxic_ratio', models.CharField(max_length=10)),
                ('severe_ratio', models.CharField(max_length=10)),
                ('obscene_ratio', models.CharField(max_length=10)),
                ('threat_ratio', models.CharField(max_length=10)),
                ('insult_ratio', models.CharField(max_length=10)),
                ('hate_ratio', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
