# Generated by Django 2.2.1 on 2019-05-25 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='message',
            name='hate_words',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='insult_words',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='obscene_words',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='severe_words',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='threat_words',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='toxic_words',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 16, 21, 40, 268344)),
        ),
    ]
