# Generated by Django 2.2.1 on 2019-05-27 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_auto_20190525_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='toxic_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 27, 12, 18, 57, 171602)),
        ),
    ]
