# Generated by Django 2.2.1 on 2019-06-01 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_auto_20190527_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='L_hate_ratio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='L_insult_ratio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='L_obscene_ratio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='L_severe_ratio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='L_threat_ratio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='L_toxic_ratio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 42, 33, 372473)),
        ),
    ]
