# Generated by Django 2.2.2 on 2019-06-10 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_auto_20190601_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 20, 49, 30, 911813)),
        ),
    ]
